<a href="https://colab.research.google.com/github/akshitamaddela16/M.Akshitha/blob/main/TNS_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **NumPy** (Numerical Python)
**Numpy is a fundamental Python library used for numerical computing. It provides support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on them efficiently.

# key feature of numpy
N-dimensional arrays (ndarray) for storing and manipulating data.
Fast mathematical operations such as addition, subtraction, multiplication, and division.
Statistical functions like mean, median, standard deviation, and variance.
Linear algebra operations, including matrix multiplication and solving equations.
Random number generation for simulations and data analysis.
Efficient memory usage and high performance compared to standard Python lists.

# create a numpy array containing numbers from 1 to 20 using inbuilt function

In [ ]:
import numpy as np

# Create a NumPy array from 1 to 20
arr = np.arange(1, 21)

print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


# create an a array of all zero's with 10 elements and convert it to matrix

In [ ]:
import numpy as np

# Create an array of 10 zeros
arr = np.zeros(10)

# Convert the array into a 2x5 matrix
matrix = arr.reshape(2, 5)

print("Array:")
print(arr)

print("\nMatrix:")
print(matrix)

Array:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

Matrix:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


#create an a array containing even numbers from 2 to 20

In [ ]:
import numpy as np

# Create an array of even numbers from 2 to 20
arr = np.arange(2, 21, 2)

print(arr)

[ 2  4  6  8 10 12 14 16 18 20]


# create an array and find number of dimensions shape, size,data type and multiple every element by 2

In [ ]:
import numpy as np

# Create a NumPy array
arr = np.array([10, 20, 30, 40, 50])

# Number of dimensions
print("Number of Dimensions:", arr.ndim)

# Shape of the array
print("Shape:", arr.shape)

# Size of the array
print("Size:", arr.size)

# Data type of the array
print("Data Type:", arr.dtype)

# Multiply every element by 2
result = arr * 2

print("Original Array:", arr)
print("Array after multiplying by 2:", result)


Number of Dimensions: 1
Shape: (5,)
Size: 5
Data Type: int64
Original Array: [10 20 30 40 50]
Array after multiplying by 2: [ 20  40  60  80 100]


# create id array and find some mean,max,min value

In [ ]:
import numpy as np

# Create a 1D array
arr = np.array([10, 20, 30, 40, 50])

# Find sum
print("Sum:", np.sum(arr))

# Find mean
print("Mean:", np.mean(arr))

# Find maximum value
print("Maximum:", np.max(arr))

# Find minimum value
print("Minimum:", np.min(arr))

Sum: 150
Mean: 30.0
Maximum: 50
Minimum: 10
